
version: '3'

http:
  address: 0.0.0.0:8080
  middleware: [gzip, headers, static]
  
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
  
  headers:
    response:
      "Access-Control-Allow-Origin": "*"
      "Access-Control-Allow-Methods": "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type, Authorization"
  
  pool:
    num_workers: 4
    command: "php worker.php"
    relay: "pipes"
    max_jobs: 1000
    supervisor:
      max_worker_memory: 256
      idle_ttl: 30s
      exec_ttl: 60s

logs:
  mode: development
  level: info
